# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_auto_20171122_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='studing_in',
        ),
    ]
