# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_profile_djangousergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aboutme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
