# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_auto_20171123_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='thumbnail',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='static/images/thumbnails'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='static/images'),
        ),
    ]
